### ISSUE TITLE
OTA stopped working with weather and websocket draw example, does not work after ftdi upload

### ISSUE THREAD

**Issue by vidax** [sqfmi/badgy#13]
Hello, I bought 5 Badgys on Tindie.
I uploaded some tests OTA on the badgies, When I tried the weather, 2 of them froze, and when I restarted a 3rd one, it froze also (it had the websocketdraw on it).
Now, I am trying to upload using FTDI, it uploads well (Blinking led, and 100% status), but still stays frozen to the last state when it stopped working.
I jumped 0 and gnd as per your chart. and left rest in the air as per your rst => NC instruction.
What do you think goes wrong? I am uploading the Badgy, and hello INO, but I cannot get it to show on the screen when i plug it back
The only one that keeps on working is the hourly quote, but I do not dare changing anything in the code, nor developing with Badgy until I can get it to work without OTA

Thank you for your help 
![img_1262](https://user-images.githubusercontent.com/745741/45547877-fe563580-b82a-11e8-8b09-9a45a2cdd986.JPG)

**Comment by sqfmi** [comment]
Hi @vidax!

Try using esptool to erase the flash and try again

```esptool.py --port <serial-port-of-FTDI> erase_flash```

or in Arduino

![image](https://user-images.githubusercontent.com/28943617/45565955-4cffd180-b823-11e8-85f6-38240dbe6a32.png)

Let us know how it goes, thanks.
