### ISSUE TITLE
@sqfmi Hmm.. Reset didn't work for me - the LED on the ESP8266 blinks when reset - but nothing. In fact, I get absolutely nothing happenng now :( sketches won't upload and the currently loaded sketch (weather) won't refresh :,( Oh, and the circled component is scortching hot -

### ISSUE THREAD

**Issue by JonPrevost** [sqfmi/badgy#28]
![20181017_215502](https://user-images.githubusercontent.com/9946962/47083319-f2abc380-d25b-11e8-8b5f-1b476e979080.jpg)

_Originally posted by @ibuildrockets in https://github.com/sqfmi/badgy/issues/20#issuecomment-430591985_

**Comment by JonPrevost** [comment]
Left on with websocketDraw example and I'm having the same problem. This is very hot and nothing is working now. It was left on for 2 days. Will not reset. The CH340C is still in-place, unmodified board.

**Comment by ibuildrockets** [comment]
I've tested the hot component. Ambient is 25ºC (77ºF) and the component is at 89ºC (192.5ºF)

Again, no life in the badge :(

![20181117_134136](https://user-images.githubusercontent.com/9946962/48655887-a24d9e80-ea71-11e8-8f8c-c2375a03b0ba.jpg)

**Comment by sqfmi** [comment]
The inductor shouldn't be that hot ♨️ ! Please try replacing it with an equivalent 68uH 1210 inductor, or reach out to us with your order number and we'll send you a replacement board.

**Comment by ibuildrockets** [comment]
Oh that's super! Tindie order number is 122802 under the name Sascha Grant.

**Comment by ibuildrockets** [comment]
@sqfmi Thank you for shipping a replacement PCB :) I've not transferred the display across yet. I've just ordered the PCB from OHS Park - What's the difference between CP2104-F03-GMR and CP2104-F03-GM - does it matter? Just wanting to get the IC on the way, too :)  Figure that I'll get that on the board first.

**Comment by sqfmi** [comment]
@ibuildrockets they should both be the same, just different packaging. Closing this issue now.
