### ISSUE TITLE
GxEPD repo does not package ZIP files for use of Hello example

### ISSUE THREAD

**Issue by sanecito** [sqfmi/badgy#3]
In the badgy example it says to include the library from https://github.com/ZinggJM/GxEPD. All the other libraries we need to include have zip bundled releases, but GxEPD doesn't. How do we install GxEPD w/o using a .zip file?

Can we use the Adafruit EPD by Adafruit (v1.0.1) library that's findable via the Library Manager instead?

**Comment by Ryomoo** [comment]
Download the master branch as .zip and install it in adruino.

**Comment by sqfmi** [comment]
Hi @sanecito is this resolved? If so, we'd like to close this issue.

**Comment by pastorhudson** [comment]
[Here's the instructions to get the correct branch: https://github.com/sqfmi/badgy/issues/18#issuecomment-429561161](https://github.com/sqfmi/badgy/issues/18#issuecomment-429561161)
