### ISSUE TITLE
Can Badgy measure the voltage of the battery?

### ISSUE THREAD

**Issue by mrWheel** [sqfmi/badgy#37]
Is it possible (with minor modifications, if needed) to measure the voltage of the battery?

**Comment by chunkysteveo** [comment]
You can - jumper the ADC pads on the back and that will give you the voltage as an analogue readout using the built in ADC of the ESP8266 chip.

**Comment by sqfmi** [comment]
Moved to Wiki https://github.com/sqfmi/badgy/wiki/Can-Badgy-measure-the-voltage-of-the-battery%3F

**Comment by chunkysteveo** [comment]
Adding to this all the way in 2022(!) Bridging the ADC solder jumper will only measure up to 3.3V as the voltage divider is 220k/100k - to get a more accurate battery voltage you should bridge the ADC jumper with a 100k resistor, which will bring the recorded ADC value closer to 4.2V when at or near 1V seen on the ADC ( voltage divider will be  = 320k / 100k).
