### ISSUE TITLE
Fatal error occurred with esptool.py after erase_flash

### ISSUE THREAD

**Issue by Jaharmi** [sqfmi/badgy#43]
I just received my Badgy. I installed a LIR2450 battery, started it up, and played with the defaults. The screen responded to the button and joystick.

I wanted to install MicroPython right away so I followed instructions to get esptool.py for my Mac running macOS 10.14.6. I also installed the SIL USB driver.

I was able to get the “erase_flash” command to work.

```
esptool.py v2.7
Found 5 serial ports
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_
Detecting chip type... ESP8266
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 84:f3:eb:84:64:fc
Uploading stub...
Running stub...
Stub running...
Erasing flash (this may take a while)...
Chip erase completed successfully in 7.1s
Hard resetting via RTS pin...
```

After that, all of my attempts to do anything — erase_flash or write_flash — with esptool.py have failed.

```
esptool.py v2.7
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header
```

I have tried turning the Badgy off, holding the button down while turning it on, and other tips/tricks I’ve come across in the issues. I’ve tried various baud rates, all the way down to 9600.

Other notes:

- The screen does not flash when I turn the Badgy on
- The screen is stuck on the last thing I did (“You pressed the right button!”), which is now taunting me
- The charging LED comes on when I plug into USB on my computer, but I’ve seen it both bright and dim
- An LED next to the ESP-12F flashes immediately after turning the Badgy on but is off in an instant
- **update:** I saw the device’s Wi-Fi network initially, but no longer see it

**Comment by chunkysteveo** [comment]
Can you upload a sketch via Arduino IDE like a "classic" ESP8266 project? i.e. not using Micropython or ESPtool?

**Comment by Jaharmi** [comment]
I don’t know if I did this correctly, but I tried File > Examples > 01.Basics > Blink. I clicked the Upload button, it compiled, it tried to upload with esptool.py (2.6, which looks like it’s in the app bundle for the Arduino app), and got the same error.

**Comment by chunkysteveo** [comment]
No, you will need to install the ESP8266 boards with the Arduino Board Manager. It's quite a lengthy process....

I'm not a Python man, so can't advise much further, sorry.

**Comment by Jaharmi** [comment]
I did install the ESP8266 v2.5.2 in the Boards Manager, if that’s needed. It didn’t seem to be a lengthy process. Afterward, I selected the NODEMCU 1.0 and I think the Tools menu changed significantly. It gives information on what I assume is the Badgy.

![ArduinoIDEToolsMenuAfterNODEMCU](https://user-images.githubusercontent.com/214152/63607981-ccecfa80-c5a1-11e9-9d2e-00f09d700fa3.png)
