### ISSUE TITLE
[micropython] update example for the latest display

### ISSUE THREAD

**Issue by dadokkio** [sqfmi/badgy#48]
Hi, not sure why there is no "new issues" on badgy-python so I'll open the issue here.

Is "epaper2in9.py" working with the latest revision of badgy? 
There is an updated "greyscale" demo available also for micropython?

Thanks.

**Comment by sqfmi** [comment]
Updated in https://github.com/sqfmi/badgy-python

**Comment by dadokkio** [comment]
I tried to print an image following the arduino grayscale tutorial for creating the image array.
Not sure if the setting are correct (16 color?) but the image seems to be huge.
Secondly, if I need to write light gray or dark gray text there is an example on how to do that?

Thanks

**Comment by dadokkio** [comment]
I made also other test plotting lines and text with framebuffer but the only way to render them correctly is with framebuf.MONO_HLSB with badgy in portrait mode.
