### ISSUE TITLE
Console log not showing anything in Serial (COM port)

### ISSUE THREAD

**Issue by Dacesilian** [sqfmi/badgy#50]
I'm trying to debug my program (badgy connected with USB), so I'm using this in `setup()` method:
```
Serial.begin(115200);
Serial.println("Setup");
display.init(115200);
```
But nothing is showing in terminal (only unreadable characters on boot).

Is Serial supported? Is speed 115200 okay? I've tried 9600 as well, but the same result.
When I open Tools -> Serial monitor (in Arduino IDE), badgy does not restart (as other devices do).

I'm using latest revision 2C.

Thanks.

**Comment by sqfmi** [comment]
If you call display.init with a baud rate, it will try to initialize the Serial port again. Try just calling display.init() without a parameter. Serial is supported and 115200 should be fine.

**Comment by Dacesilian** [comment]
Yes, I've excluded Serial.begin, as it is defined also in display.init(115200), but no text in console.

![image](https://user-images.githubusercontent.com/823994/71714634-f438bb80-2e0e-11ea-8ad9-2e9ffed4d18a.png)

![image](https://user-images.githubusercontent.com/823994/71714605-d408fc80-2e0e-11ea-968c-ccd007e00419.png)

![image](https://user-images.githubusercontent.com/823994/71714615-db300a80-2e0e-11ea-891c-cec655e5e44b.png)

![image](https://user-images.githubusercontent.com/823994/71714623-e125eb80-2e0e-11ea-8cc2-e41c0c07f329.png)

There was a readable text in console when connecting to WiFi, but my Serial.println is beeing ignored.

**Comment by Dacesilian** [comment]
I've made a few tests and my observation is that console is fine with this code:

```
#include <GxEPD.h>
#include <GxGDEW029T5/GxGDEW029T5.h>
#include <GxIO/GxIO_SPI/GxIO_SPI.h>
#include <GxIO/GxIO.h>

GxIO_Class io(SPI, SS, 0, 2);
GxEPD_Class display(io); // default selection of D4, D2

void setup() {
  display.init(115200); // enable diagnostic output on Serial
  display.setRotation(3);
  Serial.println("Setup");
  Serial.print("..... :) .....");
  Serial.println();

  /*pinMode(1, INPUT_PULLUP); //down
    pinMode(3, INPUT_PULLUP); //left
    pinMode(5, INPUT_PULLUP); //center
    pinMode(12, INPUT_PULLUP); //right
    pinMode(10, INPUT_PULLUP); //up*/

  Serial.println("Setup done, yeah");
}
```
![image](https://user-images.githubusercontent.com/823994/71720481-315a7900-2e22-11ea-8f0b-7f6cf591c785.png)

But when I enable pinMode lines, it won't show anything (even not timestamp in console):
![image](https://user-images.githubusercontent.com/823994/71720522-5353fb80-2e22-11ea-90ef-b6520692972b.png)

**Comment by chunkysteveo** [comment]
Ahh yes. The button is using the TX/RX pins. When you enable them, they are inputs, so no serial protocol output. I am sure I saw in some readme that you can't use serial output if using buttons - a vague memory I think??!

Steve

**Comment by chunkysteveo** [comment]
The shared pins with TX/RX for the buttons is a limitation of the ESP8266 module and the fact the paper display needs so many pins to operate. It's either use serial output, or use buttons, not both.

**Comment by chunkysteveo** [comment]
Found it - [https://github.com/sqfmi/badgy/issues/27#issuecomment-434373427](https://github.com/sqfmi/badgy/issues/27#issuecomment-434373427)

**Comment by Dacesilian** [comment]
Thanks, it's clear now. It's sad.
