### ISSUE TITLE
Can Badgy charge LiPo batteries?

### ISSUE THREAD

**Issue by AlanCunningham** [sqfmi/badgy#60]
I'm considering soldering on a JST-PH header breakout to use with a LiPo battery. 

The charging circuit can charge LIR2450 coin batteries. Can it also charge LiPo batteries, or would I need a separate charger for this?

Thanks!

**Comment by chunkysteveo** [comment]
Yes, the built in charging circuit is for LiPo.

**Comment by AlanCunningham** [comment]
Amazing, thanks for confirming!
